name: 08-Multi-Job

on:
  push:
    paths:
      - '.github/workflows/task8.yaml'   # only triggers when files in task8/ folder change

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test"