name: 10-Secrets
on:
  push:
    paths:
      - '.github/workflows/task10.yaml'
 
jobs:
  secrets:
    runs-on: ubuntu-latest
    env:
      APP: Mypassword
    steps:
      - run: echo "${{ secrets.API_KEY }}"