on:[push]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        - run: pipi install -r requiements.txt
        - run: pytest